development:
    host: localhost
    adapter: mysql
    database: db
    username: username
    password: passwd
    
production:
    host: localhost
    adapter: mysql
    database: db
    username: username
    password: passwd
